server:
  port: 8888

spring:
  application:
    name: centralized-config

  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_REPO_URI}
          search-paths:
            - services/centralized-config/src/main/resources/configs

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
