server:
  port: ${API_GATEWAY_PORT:8080}

logging:
  level:
    io.opentelemetry.exporter: ERROR
    io.opentelemetry.exporter.internal.http.HttpExporter: ERROR

shop-service:
  address: http://${SHOP_SVC_HOST:shop-service}:${SHOP_SVC_API_PORT:8081}
auth-service:
  address: http://${AUTH_SERVICE_HOST:auth-service}:${AUTH_SVC_API_PORT:8082}
inventory-service:
  address: http://${INVENTORY_SVC_HOST:inventory-service}:${INVENTORY_SVC_API_PORT:8083}


spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          forwarded: enabled

    loadbalancer:
      config:
        default:
          caseInsensitiveServiceId: true


management:
  tracing: { enabled: false }
  otlp:
    tracing:
      endpoint: ${TEMPO_PUSH_API_ENDPOINT:http://tempo-distributor:4318/v1/traces}
    metrics:
      export: { enabled: false }
