logging:
  level:
    com.example.inventory: DEBUG
    org.springframework.r2dbc: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: INFO

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis-master}
      port: ${REDIS_PORT:6379}
