logging:
  level:
    com.example.inventory: DEBUG

order-system:
  workers:
    product-reservation-sync-requests-handler:
      schedule-rate-ms: 15000
  messaging:
    product-reservation-requests:
      topic-partitions: "0-2"
      timeout-seconds: 15
      track-max-requests: 1000
    product-reservation-sync-requests:
      topic-partitions: "0-2"
      timeout-seconds: 15
      batch-size: 150
      request-expires-after-ms: 15000

spring:
  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - "${REDIS_HOST}:${REDIS_SENTINEL_PORT}"

#management:
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0