logging:
  level:
    org.hibernate: INFO
    org.springframework.r2dbc: INFO
    com.example.inventory: DEBUG

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis-master}
      port: ${REDIS_PORT:6379}
